name: conda

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    name: conda ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Minoconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          python-version: 3.8

      - name: Set-up channels and install conda build
        run: |
          mamba install -y conda-build conda-verify
        shell: bash

      - name: build and test package
        run: |
          cd .conda
          mamba build . --no-anaconda-upload
        shell: bash
